services:
  db:
    image: postgres:latest
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=hrms
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - hrms_db_data:/var/lib/postgresql/data/pgdata
    restart: always

  portainer:
    container_name: Portainer
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped


volumes:
  hrms_db_data:
  portainer_data: