services:
  # hrms_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: hrms_app
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./hrms/.env
  #   # volumes:
  #   #   - ./hrms/.env:/app/.env
  #   # environment:
  #   #   - DB_HOST=db
  #   #   - DB_PORT=5432
  #   #   - DB_USER=postgres
  #   #   - DB_PASSWORD=hrms
  #   #   - DB_NAME=postgres
  #   #   # - SECRET_KEY=V-YWu6ClrSOjaJ_BgXq4zwK9KUy7poM5H11hCg5H0ypuN0gUVaa6oh99-zljjXd1t7WMGd8zl_eloSJXecgjHA
  #   #   # - REFRESH_SECRET_KEY=ZIGz5X1j4hzHhyHriZE71f07SRuBNoptVRC_IIpFwu_Jpu6WArCmNA5OqskE7FDpYSY6dzWmYzYDDeLDFbsJNA
  #   depends_on:
  #     - db
  #   restart: always

  db:
    image: postgres:latest
    ports: 
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=hrms
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - hrms_db_data:/var/lib/postgresql/data/pgdata
    restart: always

  # portainer:
  #   container_name: Portainer
  #   image: portainer/portainer-ce:latest
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - portainer_data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   restart: unless-stopped


volumes:
  hrms_db_data:
  # portainer_data: