"""auto migration

Revision ID: 07997be6dbeb
Revises: bf160336ccbb
Create Date: 2025-11-17 20:32:40.609053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07997be6dbeb'
down_revision: Union[str, Sequence[str], None] = 'bf160336ccbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ir_hr_field', 'model_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ir_hr_field', 'model_id',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
