"""Adding relationships

Revision ID: 601a14294984
Revises: 8a89f9955025
Create Date: 2025-12-08 19:26:47.642436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601a14294984'
down_revision: Union[str, Sequence[str], None] = '8a89f9955025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ir_hr_group_role_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ir_hr_group.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['ir_hr_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ir_hr_group_role_rel')
    # ### end Alembic commands ###
