"""auto migration

Revision ID: 81f8ae4b318b
Revises: 44417872741c
Create Date: 2025-11-17 17:29:53.272637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f8ae4b318b'
down_revision: Union[str, Sequence[str], None] = '44417872741c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_employee', sa.Column('dep_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_employee', 'dep_name')
    # ### end Alembic commands ###
