"""Status column made to nullable true in hr_employee

Revision ID: 8fc7985b8c22
Revises: aa2f7e5c82e9
Create Date: 2025-12-05 17:19:44.368686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fc7985b8c22'
down_revision: Union[str, Sequence[str], None] = 'aa2f7e5c82e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hr_employee', 'status',
               existing_type=postgresql.ENUM('draft', 'submitted', 'approved', 'rejected', name='status_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hr_employee', 'status',
               existing_type=postgresql.ENUM('draft', 'submitted', 'approved', 'rejected', name='status_enum'),
               nullable=False)
    # ### end Alembic commands ###
