"""First Migration

Revision ID: aa2f7e5c82e9
Revises: 7c990a1cab0e
Create Date: 2025-12-04 16:55:21.122302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa2f7e5c82e9'
down_revision: Union[str, Sequence[str], None] = '7c990a1cab0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_expense',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hr_expense')
    # ### end Alembic commands ###
