"""auto migration

Revision ID: bf160336ccbb
Revises: 81f8ae4b318b
Create Date: 2025-11-17 17:33:44.163458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf160336ccbb'
down_revision: Union[str, Sequence[str], None] = '81f8ae4b318b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ir_hr_model', sa.Column('view_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ir_hr_model', 'view_id')
    # ### end Alembic commands ###
