"""First migration

Revision ID: 7954d51cc9bb
Revises: 
Create Date: 2025-12-15 12:44:12.993364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7954d51cc9bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_department',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('hr_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emp_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('Another Phonenumber', sa.String(length=15), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'rejected', name='status_enum'), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('job_title', sa.String(length=128), nullable=True),
    sa.Column('dep_name', sa.String(length=128), nullable=True),
    sa.Column('employee_type', sa.Enum('CONTRACT', 'PERMANENT', name='employee_type_enum'), nullable=True),
    sa.Column('employee_group_type', sa.Enum('G1', 'G2', name='employee_group_type_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Another Phonenumber'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('hr_payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('payroll', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('res_model', sa.String(length=128), nullable=True),
    sa.Column('res_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_cron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('method', sa.String(length=128), nullable=True),
    sa.Column('interval_type', sa.String(length=32), nullable=True),
    sa.Column('interval_number', sa.Integer(), nullable=True),
    sa.Column('nextcall', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ir_hr_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('view_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ir_hr_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ir_hr_sequence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=True),
    sa.Column('padding', sa.Integer(), nullable=True),
    sa.Column('next_number', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_setting',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=10), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('res_model', sa.String(length=128), nullable=True),
    sa.Column('res_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('attendance', sa.Float(), nullable=True),
    sa.Column('leaves_type', sa.Enum('SICK', 'ANNUAL', 'HAJJ', name='leavetypeenum'), nullable=True),
    sa.Column('attendance_left', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_attendance_id'), 'hr_attendance', ['id'], unique=False)
    op.create_table('hr_expense',
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee.id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_table('hr_fuel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('fuel_amount', sa.Double(), nullable=True),
    sa.Column('fuel_type', sa.Enum('petrol', 'cng', name='fuel_type'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hr_salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('basic_salary', sa.Integer(), nullable=True),
    sa.Column('allowances', sa.Integer(), nullable=True),
    sa.Column('deductions', sa.Integer(), nullable=True),
    sa.Column('net_salary', sa.Integer(), nullable=True),
    sa.Column('employee_bonus', sa.Enum('PROVIDENDFUND', 'EIS', name='emp_bonus_enum'), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['hr_employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('perm_read', sa.Boolean(), nullable=True),
    sa.Column('perm_write', sa.Boolean(), nullable=True),
    sa.Column('perm_create', sa.Boolean(), nullable=True),
    sa.Column('perm_unlink', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ir_hr_group.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ir_hr_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.String(length=64), nullable=False),
    sa.Column('string', sa.String(length=128), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('readonly', sa.Boolean(), nullable=True),
    sa.Column('relation', sa.String(length=128), nullable=True),
    sa.Column('help', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ir_hr_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_group_role_rel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ir_hr_group.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['ir_hr_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=64), nullable=True),
    sa.Column('template_path', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ir_hr_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('domain_filter', sa.Text(), nullable=True),
    sa.Column('global_rule', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ir_hr_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ir_hr_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ir_hr_users_email'), 'ir_hr_users', ['email'], unique=True)
    op.create_table('ir_hr_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('view_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('view_type', sa.String(length=64), nullable=True),
    sa.Column('xml_data', sa.Text(), nullable=True),
    sa.Column('json_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ir_hr_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('view_id')
    )
    op.create_table('ir_hr_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('view_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['ir_hr_model.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['ir_hr_report.id'], ),
    sa.ForeignKeyConstraint(['view_id'], ['ir_hr_view.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_hr_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('action_model', sa.String(length=128), nullable=True),
    sa.Column('action_view_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['action_view_id'], ['ir_hr_view.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['ir_hr_menu.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ir_hr_menu')
    op.drop_table('ir_hr_action')
    op.drop_table('ir_hr_view')
    op.drop_index(op.f('ix_ir_hr_users_email'), table_name='ir_hr_users')
    op.drop_table('ir_hr_users')
    op.drop_table('ir_hr_rule')
    op.drop_table('ir_hr_report')
    op.drop_table('ir_hr_group_role_rel')
    op.drop_table('ir_hr_field')
    op.drop_table('ir_hr_access')
    op.drop_table('hr_salary')
    op.drop_table('hr_fuel')
    op.drop_table('hr_expense')
    op.drop_index(op.f('ix_hr_attendance_id'), table_name='hr_attendance')
    op.drop_table('hr_attendance')
    op.drop_table('ir_hr_translation')
    op.drop_table('ir_hr_setting')
    op.drop_table('ir_hr_sequence')
    op.drop_table('ir_hr_role')
    op.drop_table('ir_hr_model')
    op.drop_table('ir_hr_log')
    op.drop_table('ir_hr_group')
    op.drop_table('ir_hr_cron')
    op.drop_table('ir_hr_attachment')
    op.drop_table('hr_payroll')
    op.drop_table('hr_employee')
    op.drop_table('employee_department')
    # ### end Alembic commands ###
