from . import ir_hr_model
from . import ir_hr_fields
from . import ir_hr_view
from . import ir_hr_menu
from . import ir_hr_reports
from . import ir_hr_actions
from . import ir_hr_rules
from . import ir_hr_group
from . import ir_hr_access
from . import ir_hr_sequence
from . import ir_hr_settings
from . import ir_hr_translation
from . import ir_hr_log
from . import ir_hr_attachment
from . import ir_hr_cron
